%%{init: {'flowchart': {'curve': 'linear'}}}%%
graph LR
    subgraph N0 ["Unassigned"]
        N1("📄 exception.py")
        N2("📄 __init__.py")
        N3("📄 __main__.py")
        N4("📄 app.py")
        N5("📄 entry_point.py")
        N6("📄 __init__.py")
        N7("📄 __init__.py")
        N8("📄 __init__.py")
        N9("📄 __init__.py")
        N10("📄 __init__.py")
        N11("📄 __init__.py")
        N12("📄 json_schema_generator.py")
        N13("📄 override_dictionary.py")
        N14("📄 __init__.py")
        N15("📄 base.py")
        N16("📄 custom_error_types.py")
        N17("📄 __init__.py")
        N18("📄 custom_connection.py")
        N19("📄 __init__.py")
        N20("📄 bullet.py")
        N21("📄 education.py")
        N22("📄 experience.py")
        N23("📄 normal.py")
        N24("📄 numbered.py")
        N25("📄 one_line.py")
        N26("📄 reversed_numbered.py")
        N27("📄 __init__.py")
        N28("📄 __init__.py")
        N29("📄 font_family.py")
        N30("📄 __init__.py")
        N31("📄 __init__.py")
        N32("📄 __init__.py")
    end
    subgraph N33 ["create_theme_command & new_command"]
        N34("📄 copy_templates.py")
    end
    subgraph N35 ["create_theme_command & new_command & render_command"]
        N36("📄 error_handler.py")
        N37("📄 variant_pydantic_model_generator.py")
        N38("📄 yaml_reader.py")
        N39("📄 section.py")
        N40("📄 built_in_design.py")
        N41("📄 classic_theme.py")
        N42("📄 color.py")
        N43("📄 typst_dimension.py")
        N44("📄 locale.py")
    end
    subgraph N45 ["create_theme_command"]
        N46("📄 create_init_file_for_theme.py")
        N47("📄 create_theme_command.py")
    end
    subgraph N48 ["new_command & render_command"]
        N49("📄 new_command.py")
        N50("📄 print_welcome.py")
        N51("📄 rendercv_model_builder.py")
        N52("📄 sample_generator.py")
        N53("📄 path.py")
        N54("📄 rendercv_model.py")
        N55("📄 validation_context.py")
        N56("📄 cv.py")
        N57("📄 social_network.py")
        N58("📄 publication.py")
        N59("📄 entry_with_complex_fields.py")
        N60("📄 entry_with_date.py")
        N61("📄 design.py")
        N62("📄 settings.py")
    end
    subgraph N63 ["render_command"]
        N64("📄 parse_override_arguments.py")
        N65("📄 progress_panel.py")
        N66("📄 render_command.py")
        N67("📄 run_rendercv.py")
        N68("📄 watcher.py")
        N69("📄 html.py")
        N70("📄 markdown.py")
        N71("📄 path_resolver.py")
        N72("📄 pdf_png.py")
        N73("📄 typst.py")
        N74("📄 connections.py")
        N75("📄 date.py")
        N76("📄 entry_templates_from_input.py")
        N77("📄 footer_and_top_note.py")
        N78("📄 markdown_parser.py")
        N79("📄 model_processor.py")
        N80("📄 string_processor.py")
        N81("📄 templater.py")
        N82("📄 pydantic_error_handling.py")
        N83("📄 entry.py")
        N84("📄 english_locale.py")
        N85("📄 render_command.py")
    end
    style N34 fill:#1b9e77,stroke:#333,stroke-width:2px,color:#000;
    style N33 fill:#1b9e7733,stroke:#1b9e77,stroke-width:2px,color:#000;
    style N36 fill:#d95f02,stroke:#333,stroke-width:2px,color:#000;
    style N37 fill:#d95f02,stroke:#333,stroke-width:2px,color:#000;
    style N38 fill:#d95f02,stroke:#333,stroke-width:2px,color:#000;
    style N39 fill:#d95f02,stroke:#333,stroke-width:2px,color:#000;
    style N40 fill:#d95f02,stroke:#333,stroke-width:2px,color:#000;
    style N41 fill:#d95f02,stroke:#333,stroke-width:2px,color:#000;
    style N42 fill:#d95f02,stroke:#333,stroke-width:2px,color:#000;
    style N43 fill:#d95f02,stroke:#333,stroke-width:2px,color:#000;
    style N44 fill:#d95f02,stroke:#333,stroke-width:2px,color:#000;
    style N35 fill:#d95f0233,stroke:#d95f02,stroke-width:2px,color:#000;
    style N46 fill:#ff595e,stroke:#333,stroke-width:2px,color:#000;
    style N47 fill:#ff595e,stroke:#333,stroke-width:2px,color:#000;
    style N45 fill:#ff595e33,stroke:#ff595e,stroke-width:2px,color:#000;
    style N49 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    style N50 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    style N51 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    style N52 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    style N53 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    style N54 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    style N55 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    style N56 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    style N57 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    style N58 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    style N59 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    style N60 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    style N61 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    style N62 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    style N48 fill:#7570b333,stroke:#7570b3,stroke-width:2px,color:#000;
    style N64 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N65 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N66 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N67 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N68 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N69 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N70 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N71 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N72 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N73 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N74 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N75 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N76 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N77 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N78 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N79 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N80 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N81 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N82 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N83 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N84 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N85 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
    style N63 fill:#8ac92633,stroke:#8ac926,stroke-width:2px,color:#000;
    subgraph Legend
        N86["create_theme_command"]
        style N86 fill:#ff595e,stroke:#333,stroke-width:2px,color:#000;
        N87["new_command"]
        style N87 fill:#ffca3a,stroke:#333,stroke-width:2px,color:#000;
        N88["render_command"]
        style N88 fill:#8ac926,stroke:#333,stroke-width:2px,color:#000;
        N89["create_theme_command & new_command"]
        style N89 fill:#1b9e77,stroke:#333,stroke-width:2px,color:#000;
        N90["create_theme_command & new_command & render_command"]
        style N90 fill:#d95f02,stroke:#333,stroke-width:2px,color:#000;
        N91["new_command & render_command"]
        style N91 fill:#7570b3,stroke:#333,stroke-width:2px,color:#000;
    end